language: c
dist: trusty
sudo: required
os:
- linux
before_install:
- sudo apt-get update -y
- sudo apt-get install git automake lzop bison gperf build-essential zip curl zlib1g-dev
  g++-multilib python-networkx libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev
  squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven openjdk-8-jdk
- sudo apt-get install -y ccache &&echo 'export PATH="/usr/lib/ccache:$PATH"' | tee
  -a ~/.bashrc &&source ~/.bashrc && echo $PATH
- export USE_CCACHE=1
before_script:
- git clone "https://bitbucket.org/UBERTC/aarch64-linux-android-4.9" "$HOME/UBERTC"
- git clone --depth=50 --branch=master https://github.com/psycho-source/Psycho-Kernel
  $HOME/kernel
script:
- export KBUILD_BUILD_USER="Psycho-Mods"
- export KBUILD_BUILD_HOST="Psycho-Kernel"
- export ARCH=arm64
- export SUBARCH=arm64
- export CROSS_COMPILE="$HOME/UBERTC/bin/aarch64-linux-android-"
- cd $HOME/kernel
- make clean && make mrproper
- make x500_defconfig
- make -j8